/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_QxsAhg80E",
    "aws_user_pools_web_client_id": "dli8i3nc5m9uighph98nf30k6",
    "oauth": {
        "domain": "sampath.auth.ap-south-1.amazoncognito.com"
    }
};


export default awsmobile;
